spring: 
    profiles: 
        active:
           - dev
---
spring:
    profiles: dev
    application:
        name: springcloud-config-hao-dev
---
spring:
    profiles: test
    application:
        name: springcloud-config-hao-test